export default {
  HOMEPAGE: '/',
  DASHBOARD: '/dashboard',
  COMPANY: '/companys',
  PROJECT: '/projects',
  NOTIFY: '/notify',
  SETTING: '/setting',
  LOGIN: '/login',
  REGISTER: '/register',
  CERTIFICATION: '/Certification',
  POLICY: '/Policy',
  PROVISION: '/Provision',
  SOLUTION: '/Solution',
  PRICE: '/PriceList',
  CHANGE_PASSWORD: '/change-password',
  PACKAGES: '/packages',
  PROCEDURE: '/procedure',
  USER: '/user',
  PROJECT_DETAILS: '/projects/details',
  COMPANY_DETAILS: '/company/details',
  COMPANY_ADDNEW: '/company/add-new',
  PROJECT_ADDNEW: '/projects/add-new',
  KPI_DAY: '/kpi/day',
  KPI_SETTINGS: '/kpi/settings',
  KPI_MONTH: '/kpi/montth',
  NOTES: '/notes',
  REPORTS: '/reports',
};
