export default {
  HOMEPAGE: '/',
  DASHBOARD: '/dashboard',
  COMPANY: '/companys',
  PROJECT: '/projects',
  NOTIFY: '/notify',
  SETTING: '/setting',
  LOGIN: '/login',
  REGISTER: '/register',
  PACKAGES: '/packages',
  REPORT: '/report',
  PROCEDURE: '/procedure',
  USER: '/user',
  PROJECT_DETAILS: '/projects/details',
  COMPANY_DETAILS: '/company/details',
  PROJECT_ADDNEW: '/projects/add-new',
  KPI_DAY: '/kpi/day',
  KPI_MONTH: '/kpi/montth',
};
